#!/bin/sh

# Show wifi percent

# Slight changes to wording

case $BLOCK_BUTTON in
	1) "$TERMINAL" -e nmtui; pkill -RTMIN+4 dwmblocks ;;
	3) notify-send "Internet module." "\- Click to connect
" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

if grep -xq 'up' /sys/class/net/w*/operstate 2>/dev/null ; then
	wifiicon="$(awk '/^\s*w/ { print "Internet:", int($3 * 100 / 70) "% " }' /proc/net/wireless)"
elif grep -xq 'down' /sys/class/net/w*/operstate 2>/dev/null ; then
	grep -xq '0x1003' /sys/class/net/w*/flags && wifiicon="No Internet"
fi

printf "%s%s%s\n" "$wifiicon" "$(sed "s/down/E;s/up/'Yes Ethernet'/" /sys/class/net/e*/operstate 2>/dev/null)" "$(sed "s/.*/'VPN'/" /sys/class/net/tun*/operstate 2>/dev/null)"
